[package]
name = "monitor"
version = "0.1.0"
authors = ["chxry"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.16.4"
termion = "1.5.6"
